services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    entrypoint: /djangofileapi/server-entrypoint.sh
    expose:
      - 8000
    volumes:
      - static_volume:/djangofileapi/staticfiles
      - media_volume:/djangofileapi/mediafiles
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/djangofileapi/staticfiles
      - media_volume:/djangofileapi/mediafiles
    depends_on:
      - web
  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6381'
    ports:
      - '6381:6381'
  celery:
    restart: always
    build: .
    command: celery -A djangofileapi worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
volumes:
  static_volume:
  media_volume: